---
name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
exclude-labels:
  - release
  - skip-changelog
  - sync
categories:
  - title: 💥 Breaking Changes
    labels:
      - major
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - patch
      - fix
      - bugfix
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
      - github-actions
      - maintenance
      - tools
      - non-functional
    collapse-after: 5
  - title: 🛠️ Dependencies
    labels:
      - dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: \<*_&
template: |
  ## Changes

  $CHANGES

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
      - bug
  default: major

exclude-contributors:
  - '@dependabot'
  - dependabot
  - app/dependabot
  - dependabot[bot]
  - '@pre-commit-ci'
  - pre-commit-ci
  - app/pre-commit-ci
  - pre-commit-ci[bot]
