---
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
exclude-labels:
  - release
  - skip-changelog
  - sync
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - chore
      - 'dependencies'
      - 'github-actions'
      - maintenance
      - tools
    collapse-after: 5
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## Changes

  $CHANGES

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
      - 'bug'
  default: major

exclude-contributors:
  - '@dependabot'
  - 'dependabot'
  - 'dependabot[bot]'
  - '@pre-commit-ci'
  - 'pre-commit-ci'
  - 'pre-commit-ci[bot]'
