---
  # yamllint disable rule:indentation

  - name: bug
    color: D73A4A
    description: Something isn't working

  - name: chore
    color: 8B4513
    description: Regular code maintenance

  - name: bot:delete-on-merge
    description: Delete this branch after merging (bot command)
    color: 8B0000

  - name: bot:do-not-close
    description: Do not close this PR, even if it's empty (bot command)
    color: 2C6AAB

  - name: bot:keep-updated
    from_name: keep-updated
    description: Keep this PR updated from its base branch (bot command)
    color: 87FAA6

  - name: dependencies
    description: Pull requests that update a dependency file
    color: 0366D6

  - name: documentation
    color: 0075CA
    description: Improvements or additions to documentation

  - name: enhancement
    description: New feature or request
    color: A2EEEF

  - name: feature-request
    description: New feature or request
    color: A2EEEF

  - name: github-actions
    description: Pull requests that update GitHub Actions code
    color: '000000'

  - name: hotfix
    description: Something isn't working and needs to be fixed ASAP
    color: D73A4A

  - name: major
    description: Backward-incompatible API changes
    color: FF0000

  - name: minor
    description: New functionality, backward-compatible
    color: FFA500

  - name: non-functional
    description: A non-functional change
    color: FFFFFF

  - name: patch
    description: Backward compatible bug fixes
    color: FFFF00

  - name: python
    description: Pull requests that update Python code
    color: 2B67C6

  - name: release
    description: PR for a new release
    color: C30AC6

  - name: refactor
    description: No/low functional changes
    color: 2BB9D9

  - name: skip-changelog
    description: Skip the changelog
    color: FFFFFF

  - name: sync
    color: EDEDED

  - name: tests
    description: Pull requests that update tests
    color: 0E8A16

  - name: tools
    color: '414141'
    description: PR for updating the tools used in this repo
