---
language: en

early_access: true

reviews:
  request_changes_workflow: false

  high_level_summary: true

  poem: false

  review_status: true

  collapse_walkthrough: true

  path_filters:
    - wg_utilities/**/*.py

  path_instructions:
    - path: wg_utilities/**/*.py
      instructions: >-
        Review the Python code against the PEP 8 style guide. Highlight any deviations,
        including issues with variable names, function naming conventions, line length,
        and use of spaces vs. tabs. Ensure the use of docstrings for functions and
        classes.

        Additionally, evaluate the Python code for functional efficiency and
        optimization. Identify areas where the implementation could be improved, such
        as suboptimal use of variables/memory, inefficient input/output operations, or
        any other aspects that could hinder performance. Assess the clarity and
        appropriateness of variable and function names in the context of their roles
        within the code. Examine for potential logical errors or parts of the code that
        might lead to unexpected behavior. Suggestions for enhancing the code's
        efficiency and maintainability are highly encouraged.

  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true
