---
repos:
  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.0.0
    hooks:
      - id: sync-additional-dependencies

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        always_run: true

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
        exclude: ^tests/binary_files/.*
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - "2"
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - "2"
          - --sequence
          - "4"
          - --offset
          - "2"
          - --width
          - "4096"
          - --preserve-quotes

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
        args:
          - --all

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args:
          - --strict
        additional_dependencies:
          - types-requests==2.31.0.2
          - boto3-stubs==1.28.49
          - lxml-stubs==0.4.0
          - types-flask
          - types-Pillow
          - types-setuptools==68.2.0.0
          - types-tzlocal==5.0.1.1
          - pydantic==2.4.0
          - types-PyYAML
          - types-python-dateutil
          - pytest==7.4.2
          - types-freezegun
          - async-upnp-client==0.36.1
          - types-pyjwt
          - aioresponses==0.7.4
          - types-xmltodict
          - requests-mock==1.11.0
          - python-dotenv==1.0.0
          - mypy_boto3_lambda
          - mypy_boto3_s3
          - voluptuous-stubs

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args:
          - --disable=fixme
          - --enable=useless-suppression
          - --rcfile=.pylintrc
          - --load-plugins=pylint_strict_informational
        language: python
        types:
          - python
        additional_dependencies:
          - pylint==2.17.7
          - pylint-strict-informational==0.1

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-use-type-annotations

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli==2.0.1

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
