---
repos:
  - repo: https://github.com/worgarside/pre-commit-hooks-dependency-sync
    rev: 1.1.2
    hooks:
      - id: sync-additional-dependencies
        language_version: python3.12

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args:
          - --strict
        additional_dependencies:
          - aioresponses==0.7.6
          - async-upnp-client==0.40.0
          - boto3-stubs
          - lxml-stubs
          - moto==5.0.12
          - mypy_boto3_lambda
          - mypy_boto3_s3
          - pydantic==2.8.2
          - pytest==8.3.2
          - requests-mock==1.12.1
          - types-Pillow
          - types-PyYAML
          - types-flask
          - types-freezegun
          - types-pyjwt
          - types-python-dateutil
          - types-requests
          - types-setuptools
          - types-tzlocal
          - types-xmltodict
          - voluptuous-stubs
          - paho-mqtt==2.1.0

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1000
        exclude: ^tests/binary_files/.*
      - id: check-case-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args:
          - --pytest-test-first
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
          - --indent
          - "2"
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args:
          - --mapping
          - "2"
          - --sequence
          - "4"
          - --offset
          - "2"
          - --width
          - "4096"
          - --preserve-quotes

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture

  - repo: https://github.com/fredrikaverpil/creosote
    rev: v3.0.2
    hooks:
      - id: creosote
