---
name: Create New Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-new-release:
    name: Create New Release
    if: |
      github.event_name == 'workflow_dispatch' || (
        github.event.pull_request.merged &&
        github.base_ref == 'develop' &&
        !contains(
          github.event.pull_request.labels.*.name,
          'skip-changelog'
        ) &&
        !contains(
          github.event.pull_request.labels.*.name,
          'release'
        )
      )
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/__create_new_release.yml@main
    with:
      path-to-__version__-file: wg_utilities/__init__.py
      # yamllint disable-line rule:line-length
      publish-to-test-pypi: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.user.login == 'worgarside' || github.event.pull_request.user.login == 'worgarside-dev' }}
    secrets:
      gh-token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
