---
name: Draft Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  draft_release:
    name: Draft Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo -e "\`\`\`json\n$GITHUB_CONTEXT\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-add-to-notes:
    name: Build and Add to Release Notes
    uses: ./.github/workflows/build_and_publish.yml
    with:
      build_branch: ${{ github.base_ref }}
      environment: $ENVIRONMENT
      release_tag: $RELEASE_TAG
