---
name: Production Build/Deploy

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  get-release-tag:
    name: Get Release Tag
    uses: worgarside/github-config-files/.github/workflows/__get_release_tag.yml@main
    with:
      branch-name: ${{ github.ref }}

  run-production-build:
    name: Run Production Build
    needs:
      - get-release-tag
    uses: worgarside/github-config-files/.github/workflows/__build_and_publish.yml@main
    with:
      build-branch: main
      build-type: python
      commit-build-directory: false
      environment: production
      python-version: '3.11'
      release-tag: ${{ needs.get-release-tag.outputs.release-tag }}
    secrets: inherit
