---
name: Python Unit Tests

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to run tests on
        required: true
        default: main
  workflow_call:
    inputs:
      branch:
        type: string
        description: Branch to run tests on
        required: true
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # I'm developing on macOS, so this should be covered
          # - macos-latest
        python-version:
          - '3.10'
          - '3.11'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch || github.ref }}

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: poetry install --all-extras --sync

      - name: Run Tests
        id: unit_tests
        run: poetry run pytest --cov=./ --cov-report=xml
        continue-on-error: true

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.10'
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check on UT failures
        if: steps.unit_tests.outcome != 'success'
        run: exit 1
